# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Heliware
                                 A QGIS plugin
 Heliware Plugin
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-10-09
        copyright            : (C) 2021 by Heliware
        email                : mukulsharma.ajm1997@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Heliware class from file Heliware.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Heliware_plugin import Heliware
    return Heliware(iface)
